[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "transformers>=4.0.0",
    "pytest>=8.1.0",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "pandas>=2.2.3",
    "jinja2>=3.1.4",
    "pillow>=11.0.0",
    "llama-cpp-python>=0.3.4",
    "markdownify>=0.14.1",
    "gradio>=5.8.0",
    "duckduckgo-search>=6.3.7",
    "python-dotenv>=1.0.1",
    "e2b-code-interpreter>=1.0.3",
]

[project.optional-dependencies]
dev = [
    "anthropic",
]
test = [
    "gradio-tools"
]
